---
name: Deploy Contracts
on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  push:
    branches: [ 'mainline' ]
    paths:
      - 'contracts/src/**/*.rs'
      - '.github/workflows/deploy.yml'

env:
  VERSION_CONTROL_ADDRESS: juno16enwrxhdtsdk8mkkcaj37fgp37wz0r3err4hxfz52lcdyayexnxs4468mu
  STATE_FILE: "./daemon_state.json"
  WASM_DIR: "./target/wasm32-unknown-unknown/release"
  SCHEMA_DIR: "./schema"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true
      - name: Run cargo wasm
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package counter-app --release --target wasm32-unknown-unknown
        env:
          RUSTFLAGS: '-C link-arg=-s'
        # cargo run --package scripts --bin deploy_app
      - name: Run deployment script
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --package scripts --bin deploy_app
        env:
          CHAIN: "juno"
          DEPLOYMENT: "debugging"
          NETWORK: "local"
          RUST_LOG: info
          WASM_DIR: ${{ env.WASM_DIR }}
          DAEMON_STATE_PATH: ${{ env.STATE_FILE }}

          VERSION_CONTROL_ADDRESS: ${{ env.VERSION_CONTROL_ADDRESS }}
          TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}
      - name: Upload deployment daemon state
        uses: actions/upload-artifact@v2
        with:
          name: deployment.json
          path: ${{ env.STATE_FILE }}
      - name: Upload WASM
        uses: actions/upload-artifact@v2
        with:
          # TODO: name env or from cargo
          name: counter_app.wasm
          path: ${{ env.WASM_DIR }}/counter_app.wasm

  upload-schema:
    runs-on: ubuntu-latest
    env:
      SCHEMA_FILE: $SCHEMA_DIR/counter-app.json
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true
      - name: Run cargo schema
        uses: actions-rs/cargo@v1
        with:
          command: schema

      - name: Compare the output schema file
        id: diff
        run: |
          if [ "$(git diff --ignore-space-at-eol ${{ env.SCHEMA_FILE }} | wc -l)" -eq "0" ]; then
            echo "No changes detected in ${{ env.SCHEMA_FILE }}."
            exit 0
          fi

      - name: Rename schema
        run: mv ${{ env.SCHEMA_FILE }} ${{ env.SCHEMA_DIR }}/schema.json
      - name: Create pull request
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_folder: ${{ env.SCHEMA_DIR }}
          destination_repo: 'Abstract-OS/schemas'
          # TODO: dynamic version and name
          destination_folder: testing/counter-app/0.0.1
          destination_base_branch: main
          destination_head_branch: main
          user_email: '32375605+adairrr@users.noreply.github.com'
          user_name: adairrr
          pull_request_reviewers: adairrr
