---
name: Deploy Contracts
on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  push:
    branches: [ 'mainline' ]
    paths:
      - 'contracts/src/**/*.rs'
      - '.github/workflows/schema.yml'

env:
  SCHEMA_DIR: "./schema"

jobs:
  upload-schema:
    runs-on: ubuntu-latest
    env:
      SCHEMA_FILE: $SCHEMA_DIR/counter-app.json
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true
      - name: Run cargo schema
        uses: actions-rs/cargo@v1
        with:
          command: schema

      - name: Compare the output schema file
        id: diff
        run: |
          if [ "$(git diff --ignore-space-at-eol ${{ env.SCHEMA_FILE }} | wc -l)" -eq "0" ]; then
            echo "No changes detected in ${{ env.SCHEMA_FILE }}."
            exit 0
          fi

      - name: Rename schema
        run: mv ${{ env.SCHEMA_FILE }} ${{ env.SCHEMA_DIR }}/schema.json
      - name: Create pull request
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_folder: ${{ env.SCHEMA_DIR }}
          destination_repo: 'Abstract-OS/schemas'
          # TODO: dynamic version and name
          destination_folder: testing/counter-app/0.0.1
          destination_base_branch: main
          destination_head_branch: update/counter-app/0.0.1
          user_email: '32375605+adairrr@users.noreply.github.com'
          user_name: adairrr
          pull_request_reviewers: adairrr
